name: Node.js CI

on:
  push:
    branches: [ "rework/dynamic-layouts-001" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # Voir https://nodejs.org/en/about/releases pour les versions supportées

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      # ajoute ici toutes tes variables d’environnement, si besoin

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build project (if applicable)
      run: npm run build --if-present

    - name: Run tests
      run: npm test
